### ISSUE TITLE
HTML5 Instead Of Adobe Flash

### ISSUE THREAD

**Issue by SweetLion** [vhanla/GMusicDesktopPlayer#1]
Hi,
I love your awesome desktop player! Thank you very much <3
Is it possible to use HTML5 instead of Adobe Flash?

**Comment by vhanla** [comment]
Since it uses mp3 and html5 requires to have license to play that audio format this is not possible at the moment. Google Chrome has it license, but let's hope Google would switch to an open source audio format in a near future. I'm also reading python's unofficial music API for Play Google, but I don't promise anything.
